# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
